### ISSUE TITLE
你好呀！finish_reason到底是end_turn还是stop呀？你的代码写的是end_turn，我查看了一下openai写的是stop，求指教！

### ISSUE THREAD

**Issue by GxWwT** [aws-samples/bedrock-access-gateway#11]
{"id":"chatcmpl-123","object":"chat.completion.chunk","created":1694268190,"model":"gpt-3.5-turbo-0125", "system_fingerprint": "fp_44709d6fcb", "choices":[{"index":0,"delta":{"role":"assistant","content":""},"logprobs":null,"finish_reason":null}]}

{"id":"chatcmpl-123","object":"chat.completion.chunk","created":1694268190,"model":"gpt-3.5-turbo-0125", "system_fingerprint": "fp_44709d6fcb", "choices":[{"index":0,"delta":{"content":"Hello"},"logprobs":null,"finish_reason":null}]}

....

{"id":"chatcmpl-123","object":"chat.completion.chunk","created":1694268190,"model":"gpt-3.5-turbo-0125", "system_fingerprint": "fp_44709d6fcb", "choices":[{"index":0,"delta":{},"logprobs":null,"finish_reason":"stop"}]}
上面是我从openai的官网摘下来的。

**Comment by daixba** [comment]
代码中没有写成end_turn, end_turn是 bedrock 里某些模型的api 返回的stop reason，我直接用而已。 这里并没有强制和 open ai 那边保持一致。 我测试了几个开源ai 项目， 貌似都没有检查stop reason。

如果需要完全一致，那么需要你自己对代码进行定制，我手上也没有openai 的key 可以测试。

**Comment by GxWwT** [comment]
我直接写死了，现在没有bug了。感谢。
