### ISSUE TITLE
Cohere Command R Support

### ISSUE THREAD

**Issue by kawataki-yoshika** [aws-samples/bedrock-access-gateway#12]
Are there any plans to support Cohere Command R in the model for chat?

**Comment by daixba** [comment]
There is currently no urgent plan to support this. Will update once it's ready.

**Comment by daixba** [comment]
@kawataki-yoshika Cohere Command R/R+ is now supported.  Please follow the [upgrade steps](https://github.com/aws-samples/bedrock-access-gateway#how-to-upgrade) to use the new feature.

**Comment by kawataki-yoshika** [comment]
@daixba Thank you.
I will try it right away.

**Comment by daixba** [comment]
Just a note that the default "top_p" is set to 1.0 if not provided, however, Command R/R+ can not accept 1.0 as top_p, so you should set that (to < 1.0, like `"top_p": 0.5` ) explicitly in your request.

**Comment by daixba** [comment]
Close for no updates
