### ISSUE TITLE
Need token usage when stream is true

### ISSUE THREAD

**Issue by dftty** [aws-samples/bedrock-access-gateway#28]
**Describe the bug**
usage is always null when stream is true

**Please complete the following information:**
```
curl XXX/chat/completions \
  -H "Content-Type: application/json" \
  -H "Authorization: Bearer XXX" \
  -d '{
    "model": "anthropic.claude-3-sonnet-20240229-v1:0",
    "messages": [
      {
        "role": "user",
        "content": "hi"
      }
    ],
    "stream":true,
    "max_tokens":100
  }'

```

**To Reproduce**
execute curl

**Expected behavior**
openai supply tiktoken, so i can calculate token usage when stream is true. Is there a way to add some header, so reply contain the token usage?

**Comment by ucasiggcas** [comment]
have the same problem

**Comment by daixba** [comment]
This is already supported. Make sure you have the following in your request.

```    "stream": true,
    "stream_options": {"include_usage": true},```

**Comment by ucasiggcas** [comment]
这个响应是不是不太对啊，等了几秒，后面直接出来一大坨

**Comment by daixba** [comment]
参考： https://platform.openai.com/docs/api-reference/chat/create

**Comment by ucasiggcas** [comment]
@dftty 这个我早就部署了啊，不然curl也不通的，现在的问题是stream情况下，response响应很慢，具体是curl后等待长时间才有反应，然后data数据一大堆出来了。

**Comment by ucasiggcas** [comment]
我直接将curl的东西放终端测试的，响应就是慢，不及gpt-4o

**Comment by dftty** [comment]
readme里有两种部署方式ALB + Lambda和ALB + Fargate，第一个流式是等所有数据返回才一次性返回，第二个是正常流式

**Comment by ucasiggcas** [comment]
感谢，我再建立一个堆栈试试 @dftty

**Comment by ucasiggcas** [comment]
solved ,  thx
@dftty
