### ISSUE TITLE
Support for Llama 3.1?

### ISSUE THREAD

**Issue by oemd001** [aws-samples/bedrock-access-gateway#31]
Hey, I was trying to call Llama 3.1 on the proxy, but I got a "model not supported" error. I was looking at the code and noticed that the entry for Llama 3.1 hasn't been added yet. 

https://github.com/aws-samples/bedrock-access-gateway/blob/f6b73152bc18ac229f02472be6f5cf48bf303922/src/api/models/bedrock.py#L117

Is there a timeline in which this support could be added in?

**Comment by daixba** [comment]
Sorry, have been busy recently. 

Llama 3.1 should be supported now, you can do some test.   

Note that Tool call for Llama 3.1 is not yet supported by this project, I will need more tests.

**Comment by if-igor** [comment]
How about Llama 3.2?

**Comment by kcrandall** [comment]
Any updates on llama tool calling?

**Comment by daixba** [comment]
Llama 3.1 / Llama 3.2 are now supportted, please try again and raise a new one if any further issues.

Closing this old issue.
