### ISSUE TITLE
Support for Mistral Large 2 (24.07)

### ISSUE THREAD

**Issue by diopresi** [aws-samples/bedrock-access-gateway#38]
Hey, I was trying to call Mistral Large 2 (24.07) on the proxy, but I got a "model not supported" error. I was looking at the code and noticed that the entry hasn't been added yet.

**Comment by diopres** [comment]
@daixba  create a PR #39 for this please review this as you can

**Comment by fn5** [comment]
This is still an issue:

> "Unsupported model mistral.mistral-large-2407-v1:0, please use models API to get a list of supported models"
I couldn't figure out how to make this edit myself within a deployed cloudstack.

**Comment by diopresi** [comment]
Hi @fn5,

I understand that you're looking to use the `mistral.mistral-large-2407-v1:0` model. Please ensure that this model is both available in the targeted region and enabled. 

Additionally, I want to confirm that `mistral.mistral-large-2407-v1:0` has been added to the gateway with this #39. For more details on this, you can refer to the following [How to upgrade?](https://github.com/aws-samples/bedrock-access-gateway?tab=readme-ov-file#how-to-upgrade) regarding the upgrade process.

**Comment by fn5** [comment]
Hi - the issue is that I deployed it today and it still had this error. Can someone else with it deployed check it?

**Comment by fn5** [comment]
@diopresi - apologies to come across so brashly. Is there any chance the .template file hosted on the amazon side has not updated properly? While #39 has been merged, my deployment today to us-west-2 gets this error.

**Comment by diopresi** [comment]
no prob, @fn5. i just checked, and it seems the ECR image hasn’t been updated yet, and no action has been executed on that side so far. i’ll let @daixba provide more insights or updates on this.

**Comment by daixba** [comment]
I apologize that I don't have any bandwidth to maintain this project to keep it update to date recently.  Please do host your own ecr image (there is a script for reference in the repo) and that is the recommended way to use this repo.

Sorry about this.

**Comment by daixba** [comment]
All new models are already supported. Please update the stack and try again.
Closing this issue.
