### ISSUE TITLE
Add configurable port

### ISSUE THREAD

**Issue by medvekoma** [aws-samples/bedrock-access-gateway#46]
**Is your feature request related to a problem? Please describe.**
The Dockerfile_ecs hardcodes the port `80`. Although this can be remapped to any port on a local environment, this is not an option in ECS deployments using the `awsvpc` network mode.

**Describe the feature you'd like**
An environment variable `PORT` that defaults to the earlier value of `80` to maintain compatibility, but it can be reconfigured to any value. I am going to attach a pull request.

**Additional context**
Pull request is going to be attached.

**Comment by daixba** [comment]
Code Merged. Thanks for contribution.
