### ISSUE TITLE
Custom Image returns 502 Bad Gateway

### ISSUE THREAD

**Issue by asongent** [aws-samples/bedrock-access-gateway#48]
Few things noted:
- I built my own image following the steps stipulated [here](https://github.com/aws-samples/bedrock-access-gateway?tab=readme-ov-file#can-i-build-and-use-my-own-ecr-image), but continue to receive **502 Bad Gateway**. I  was able to hit **Swagger UI** as soon as I switched the image to default.
- I wondered why access was denied while I tried pulling default image to test local deployment, but was able to use it during deployment using AWS Lambda Function.

Any help with this will be greatly appreciated

**Comment by zxkane** [comment]
The issue likely arises from building the image on x86_64, however, the Lambda/ECS require the `arm64` architecture image. #58 should resolve it.
