### ISSUE TITLE
Official Docker image

### ISSUE THREAD

**Issue by hongbo-miao** [aws-samples/bedrock-access-gateway#52]
**Is your feature request related to a problem? Please describe.**

Feature request.

**Describe the feature you'd like**

It would be great to publish official Docker image on

- GitHub Container Registry along with repo
- or public ECR

So users no need to build each time. Thanks! ☺️

**Comment by zxkane** [comment]
The Lambda container image exclusively supports images stored in ECR. For a consistent release process, both ECS and Lambda retrieve images from ECR. Additionally, the pre-built container image is published on ECR for all AWS accounts.

**Comment by hongbo-miao** [comment]
Hi @mschfh I think this repo serves as sample, for production, personally, I would recommend using https://github.com/BerriAI/litellm, so you can use any vendor, and downstream you can use any tools, it would be

AWS Bedrock, Azure, Google Vertex AI, etc. -> LiteLLM -> Open WebUI, Continue, Cline, Aider, etc.

Here is a good [tutorial](https://willdady.com/streamlining-ai-experimentation-with-open-webui-litellm-and-amazon-bedrock ☺️
