### ISSUE TITLE
Support for setting up TLS on ALB

### ISSUE THREAD

**Issue by mtrampic** [aws-samples/bedrock-access-gateway#54]
**Is your feature request related to a problem? Please describe.**
Would be good to have optional Parameters in deployment[1] scripts to have ACM / SSL configuration for gateway.

[1]https://github.com/aws-samples/bedrock-access-gateway/tree/main/deployment

**Describe the feature you'd like**
Application Load Balancer should have TLS configured with ACM.

**Additional context**
This is important to have with Data Prompts going around the Services.

**Comment by zxkane** [comment]
duplicated with #5
