### ISSUE TITLE
Support for Anthropic Sonnet 3.5 v2

### ISSUE THREAD

**Issue by orossant** [aws-samples/bedrock-access-gateway#66]
**Is your feature request related to a problem? Please describe.**
Support for recent Anthropic Sonnet 3.5 v2

**Describe the feature you'd like**
Support for recent Anthropic Sonnet 3.5 v2

**Additional context**
previous Anthropic model are available

**Comment by zxkane** [comment]
Sonnet 3.5 v2 already is supported. Also, cross-region inference is supported.

If you deployed the stack before, update it again with the latest version. Once it is done, redeploy the lambda function if you are using the Lambda version, or update the ecs service to roll out new tasks using lastest container image.
