### ISSUE TITLE
CloudFormation stack Upgrade docs (Llama 3)

### ISSUE THREAD

**Issue by justin-parker** [aws-samples/bedrock-access-gateway#7]
**Is your feature request related to a problem? Please describe.**
I am trying to use Llama 3 and see the `src` has been updated, but the template links in the README do not include these changes.

**Describe the feature you'd like**
Please describe how I can use `src` to upgrade my existing CloudFormation stacks that were created from the templates listed in the README.

**Comment by daixba** [comment]
Hi Justin,

There is no need to update cloudformation template or deployment.  Depends on which versions you are running? 
1. If it's Lambda: Please go and find the lambda handler and click deploy new image to update
2. If it's Fargate: Go to ECS console, find the cluster, go to Task tab, simply stoped the task and a new task will be launched with latest image.

Please note that there maybe a delay between the source code been changed and the ECR image been updated, feel free to clone the repo and build and host the image by yourself.  Then you have full control of the deployment. This is also the way for customization if needed.

Hope this helps. Please let me know if any further issues.

**Comment by daixba** [comment]
@justin-parker Please let me know if this issue is resolved and can be closed.

**Comment by justin-parker** [comment]
yes, you can close this issue.
thank you for your response.
