### ISSUE TITLE
Ask support for Haiku 3.5

### ISSUE THREAD

**Issue by yuanze1024** [aws-samples/bedrock-access-gateway#77]
**Is your feature request related to a problem? Please describe.**
I’m trying to estimate the height of the main object in a random image using the AWS Bedrock API. However, I noticed that Haiku 3 often makes minor errors, which is quite frustrating. I’m wondering if Haiku 3.5 is better suited for this task.

**Describe the feature you’d like**
Could you please support the **anthropic.claude-3-5-haiku-20241022-v1:0** proxy in this project? Also, if I’ve already deployed it via AWS CloudFormation, would I need to redeploy it to enable support for this version?

**Context**
When trying to call the Haiku 3.5 API, I encountered the following error:

```
Error occurred during calling Claude3 Api: Error code: 400 - {'detail': 'Unsupported model anthropic.claude-3-5-haiku-20241022-v1:0, please use models API to get a list of supported models'}  
```

Interestingly, I can call Haiku 3 successfully in the same environment. Moreover, I’m able to interact with Haiku 3.5 using the web playground, but it doesn’t work with this API proxy. This leads me to believe the issue might be related to the proxy itself.

**Comment by nonatofabio** [comment]
Simple solution before someone adds the model is to add in your local version of bedrock-access-gateway the model you need. You can add a model here:

https://github.com/aws-samples/bedrock-access-gateway/blob/main/src/api/models/bedrock.py#L112

Something like this is what you would look for:

```
"anthropic.claude-3-5-haiku-20241022-v1:0": {
            "system": True,
            "multimodal": True,
            "tool_call": True,
            "stream_tool_call": True,
        },
```

**Comment by ron137** [comment]
+1

**Comment by yuanze1024** [comment]
OK. Thank you guys for your helping!
But I just found out that the Claude3.5-haiku does not support image input and not going to use it, so I will try this when I need it again.
> "anthropic.claude-3-5-haiku-20241022-v1:0": {
            "system": True,
            "multimodal": True,
            "tool_call": True,
            "stream_tool_call": True,
        },



Still, thank you so much.
