### ISSUE TITLE
In Server-Sent Events responses, there is no token usage.

### ISSUE THREAD

**Issue by lishiyu** [aws-samples/bedrock-access-gateway#8]
In Server-Sent Events responses, there is no token usage.

**Comment by daixba** [comment]
Hello @lishiyu , thanks for raising the issue.

This will be a low priority item. The purpose of this repo is to help you quickly explore the Bedrock models capability, not all OpenAI API features will be supported.

The recommendation for you is to use Bedrock SDK instead if you need to track the token usage. Or you can do full customization on your own based on this.

**Comment by daixba** [comment]
Hello @lishiyu The usage info is now added to the streaming response. Please follow the [upgrade steps](https://github.com/aws-samples/bedrock-access-gateway#how-to-upgrade) to try the new features.

Make sure you have added `"stream_options": {"include_usage": true}` parameter to the request as per OpenAI doc.

**Comment by daixba** [comment]
Close for no updates
